FROM python:3.6

RUN pip install pipenv

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN apt-get update && apt-get install -y netcat

WORKDIR /usr/src/app

COPY . .

RUN python --version
RUN pipenv install

# Run entrypoint to ensure postgres is running in other contianer
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD []